version: '3.9'

services:
  desafio-back:
    container_name: desafio_back_api
    ports:
      - '3000:3000'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        node_env: dev
