version: '3.9'

services:
  desafio-back:
    container_name: desafio_back
    ports:
      - '3001:3001'
    build: .
    volumes:
      - .:/home/desafio-back
      - /home/desafio-back/node_modules

  mongo:
    container_name: mongo_db
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
