FROM node:18.18.0 as builder

ENV NODE_ENV build

USER node
WORKDIR /home/node

COPY package.json ./
COPY yarn.lock ./
# COPY .npmrc ./

RUN rm -rf node_modules && yarn install --frozen-lockfile

COPY --chown=node:node . .

RUN yarn build \
  && yarn install

# ---

FROM node:18.18.0

ARG node_env
RUN echo "NODE_ENV: $node_env"
ENV NODE_ENV dev

USER node
WORKDIR /home/node

COPY --from=builder --chown=node:node /home/node/package.json ./
COPY --from=builder --chown=node:node /home/node/yarn.lock ./
COPY --from=builder --chown=node:node /home/node/node_modules/ ./node_modules/
COPY --from=builder --chown=node:node /home/node/dist/ ./dist/

EXPOSE 3000

CMD ["node", "dist/src/main.js"]
