version: '3.9'

services:
  desafio-back:
    container_name: desafio_back
    ports:
      - '3001:3001'
    build: .
    volumes:
      - .:/home/desafio-back
      - /home/desafio-back/node_modules
    depends_on:
      - mongo_db
    links:
      - mongo_db

  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_USERNAME: root
      MONGO_INITDB_PASSWORD: example
      MONGO_INITDB_DATABASE: local
